[package]
name = "beetle_bits"
version = "0.2.6"
authors = ["beetle"]
edition = "2024"
description = "Types operating on bits & bytes"
license = "MIT"
repository = "https://github.com/Mearkatz/beetle_bits"

[dependencies]
num-traits = "0.2.19"
